from use_cases.AddLine.request_model import get_request_model as get_request_model_for_add_line
from use_cases.AddRectangle.request_model import get_request_model as get_request_model_for_add_rectangle
from use_cases.AddText.request_model import get_request_model as get_request_model_for_add_text
from use_cases.ChangeRectangleShape.request_model import \
    get_request_model as get_request_model_for_change_rectangle_shape
from use_cases.MoveLine.request_model import get_request_model as get_request_model_for_move_line
from use_cases.MoveRectangle.request_model import get_request_model as get_request_model_for_move_rectangle
from use_cases.MoveText.request_model import get_request_model as get_request_model_for_move_text
from use_cases.RemoveLine.request_model import get_request_model as get_request_model_for_remove_line
from use_cases.RemoveRectangle.request_model import get_request_model as get_request_model_for_remove_rectangle
from use_cases.RemoveText.request_model import get_request_model as get_request_model_for_remove_text
from use_cases.SelectShape.request_model import get_request_model as get_request_model_for_select_shape
from use_cases.SelectShapesInRange.request_model import \
    get_request_model as get_request_model_for_select_shapes_in_range
from use_cases.SetBorderColor.request_model import get_request_model as get_request_model_for_set_border_color
from use_cases.SetBorderWidth.request_model import get_request_model as get_request_model_for_set_border_width
from use_cases.SetFillColor.request_model import get_request_model as get_request_model_for_set_fill_color
from use_cases.SetLineArrow.request_model import get_request_model as get_request_model_for_set_line_arrow
from use_cases.SetLineColor.request_model import get_request_model as get_request_model_for_set_line_color
from use_cases.SetLineWidth.request_model import get_request_model as get_request_model_for_set_line_with
from use_cases.SetTextColor.request_model import get_request_model as get_request_model_for_set_text_color
from use_cases.SetTextFontSize.request_model import get_request_model as get_request_model_for_set_text_font_size
from use_cases.SetTextValue.request_model import get_request_model as get_request_model_for_set_text_value
from use_cases_high_level.AddTextBox.request_model import get_request_model as get_request_model_for_add_text_box
from use_cases_high_level.HighlightTextBox.request_model import \
    get_request_model as get_request_model_for_highlight_text_box
from use_cases_high_level.MoveTextBox.request_model import get_request_model as get_request_model_for_move_text_box
from use_cases_high_level.RemoveTextBox.request_model import get_request_model as get_request_model_for_remove_text_box

get_request_model_for_add_line = get_request_model_for_add_line
get_request_model_for_add_rectangle = get_request_model_for_add_rectangle
get_request_model_for_add_text = get_request_model_for_add_text
get_request_model_for_change_rectangle_shape = get_request_model_for_change_rectangle_shape
get_request_model_for_move_line = get_request_model_for_move_line
get_request_model_for_move_rectangle = get_request_model_for_move_rectangle
get_request_model_for_move_text = get_request_model_for_move_text
get_request_model_for_remove_line = get_request_model_for_remove_line
get_request_model_for_remove_rectangle = get_request_model_for_remove_rectangle
get_request_model_for_remove_text = get_request_model_for_remove_text
get_request_model_for_select_shape = get_request_model_for_select_shape
get_request_model_for_set_border_color = get_request_model_for_set_border_color
get_request_model_for_set_border_width = get_request_model_for_set_border_width
get_request_model_for_set_fill_color = get_request_model_for_set_fill_color
get_request_model_for_set_line_arrow = get_request_model_for_set_line_arrow
get_request_model_for_set_line_color = get_request_model_for_set_line_color
get_request_model_for_set_line_with = get_request_model_for_set_line_with
get_request_model_for_set_text_color = get_request_model_for_set_text_color
get_request_model_for_set_text_font_size = get_request_model_for_set_text_font_size
get_request_model_for_select_shapes_in_range = get_request_model_for_select_shapes_in_range
get_request_model_for_set_text_value = get_request_model_for_set_text_value

get_request_model_for_add_text_box = get_request_model_for_add_text_box
get_request_model_for_remove_text_box = get_request_model_for_remove_text_box
get_request_model_for_move_text_box = get_request_model_for_move_text_box
get_request_model_for_highlight_text_box = get_request_model_for_highlight_text_box
