package_names = [
    'src.AddRectangle',  # 0
    'src.RemoveRectangle',  # 1
    'src.MoveRectangle',  # 2
    'src.SetBorderColor',  # 3
    'src.SetBorderWidth',  # 4
    'src.SetFillColor',  # 5
    'src.AddText',  # 6
    'src.SetTextColor',  # 7
    'src.SetTextFontSize',  # 8
    'src.MoveText',  # 9
    'src.RemoveText',  # 10
    'src.AddLine',  # 11
    'src.MoveLine',  # 12
    'src.RemoveLine',  # 13
    'src.SetLineWidth',  # 14
    'src.SetLineColor',  # 15
    'src.SetLineArrow',  # 16
    'src.ChangeRectangleShape'  # 17
]
